import { ThemeConfig } from 'antd'

export const andtTheme: ThemeConfig = {
  token: {
    fontSize: 16,
    borderRadius: 12,
    controlHeight: 42,
    colorPrimary: '#db751b',
  },
  components: {
    Button: {
      colorBorder: '#fff',
      borderRadius: 50,
      fontSize: 15,
      fontWeight: 900,
    },
    Input: {
      activeBg: 'transparent',
      hoverBg: 'transparent',
      addonBg: 'transparent',
      colorBgContainer: 'transparent',
      activeBorderColor: '#fff',
      hoverBorderColor: '#fff',
      colorBorder: '#fff',
      activeShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
      inputFontSize: 18,
      borderRadius: 25,
      lineWidth: 3,
      paddingBlock: 8,
      paddingInline: 20,
    },
    Select: {
      activeBorderColor: '#fff',
      hoverBorderColor: '#fff',
      colorBorder: '#fff',
      colorBgBase: 'transparent',
      colorBgContainer: 'transparent',
      borderRadius: 25,
      lineWidth: 3,
      fontSize: 18,
      optionPadding: '8px 20px',
      optionFontSize: 15,
      controlHeight: 50,
      colorBgElevated: '#F58220',
      optionSelectedBg: '#fcc85b',
      optionSelectedColor: '#fff',
      colorPrimary: '#000',
      colorTextPlaceholder: '#fff',
      colorText: '#fff',
    },
    Checkbox: {
      fontSize: 15,
      borderRadiusSM: 10,
      controlInteractiveSize: 25,
      colorBorder: '#fff',
      colorPrimaryBorder: '#fff',
      colorBgContainer: 'transparent',
      colorPrimaryHover: '#f5821f',
      lineWidth: 3,
    },
    Card: {
      headerBg: '#58595B',
      headerFontSize: 15,
      headerHeight: 47,
    },
    Pagination: {
      itemBg: 'transparent',
      itemActiveBg: '#fff',
      itemActiveBgDisabled: 'transparent',
      colorPrimaryActive: 'transparent',
      borderRadius: 100,
      controlHeight: 50,    }
  },
}
